name: Swaply CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run ESLint
      run: npm run lint

    - name: Run npm audit
      run: npm audit --audit-level=high || true

    - name: Build project
      run: npm run build

    - name: Run tests
      run: npm test || echo "No tests configured"

    - name: Deploy to Vercel
      if: github.ref == 'refs/heads/dev'
      run: curl -X POST "$VERCEL_HOOK_DEV"
      env:
        VERCEL_HOOK_DEV: ${{ secrets.VERCEL_HOOK_DEV }}

    - name: Deploy to Vercel Production
      if: github.ref == 'refs/heads/main'
      run: curl -X POST "$VERCEL_HOOK_MAIN"
      env:
        VERCEL_HOOK_MAIN: ${{ secrets.VERCEL_HOOK_MAIN }}
